package chessagents.agents.pieceagent.behaviours.turn.fsm;

public enum PieceState {
    INITIAL,
    WAIT_FOR_MOVE,
    WAIT_FOR_LEADER,
    GAME_OVER,
    PERFORM_MOVE,
    END_TURN,
    WAIT_FOR_PROPOSAL_REQUEST,
    DECIDE_IF_REQUESTING_PROPOSALS,
    TELL_PIECE_TO_MAKE_MOVE,
    WAIT_FOR_PIECE_RESPONSE_TO_MAKE_MOVE_REQUEST,
    WAIT_FOR_MOVE_CONFIRMATION,
    HANDLE_ASKED_TO_MOVE,
    DECIDE_IF_ACTUALLY_MOVING,
    REQUEST_GAME_AGENT_MOVE_AND_AWAIT_CONFIRMATION,
}
